import React from "react";
import { Header } from "../components/Header";
import styled from "@emotion/styled";
import { SporProvider, Language } from "@vygruppen/spor-react";
import Head from "next/head";
import { MainApp } from "../components/MainApp";

const AppContainer = styled.div`
  text-align: center;
  padding: 0 20px;
  margin: 0 auto;
`;

function Index() {
  return (
    <SporProvider language={Language.English}>
      <AppContainer>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <MainApp />
      </AppContainer>
    </SporProvider>
  );
}

export default Index;
