import React from "react";
import { Header } from "../components/Header";
import styled from "@emotion/styled";
import { SporProvider, Language } from "@vygruppen/spor-react";
import Head from "next/head";
import { MainApp } from "../components/MainApp";

const AppContainer = styled.div`
  text-align: center;
  padding: 0 20px;
  margin: 0 auto;
`;

function Index({ characters }) {
  return (
    <SporProvider language={Language.English}>
      <AppContainer>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <MainApp characters={characters} />
      </AppContainer>
    </SporProvider>
  );
}

const pageLimit = 3;
let characters = [];
let pageCount = 1;
let url = "https://rickandmortyapi.com/api/character";

export async function getStaticProps() {
  while (pageCount <= pageLimit) {
    const response = await fetch(url);
    const data = await response.json();
    characters = [...characters, ...data.results];
    pageCount = pageCount + 1;
    url = data.info.next;
  }

  return {
    props: {
      characters,
    },
  };
}

export default Index;
